Repository lk-arpg/lorekeeper, pull requests merged in 2021-04, with the labels that each got.

#89 add new site settings with one line instead of multiple.
  app/Console/Commands/AddSiteSettings.php
Labels: needs review

#90 Fixing +CURRENCY count when it should be -CURRENCY
  resources/views/user/_currency_log_row.blade.php
Labels: reviewed

#97 Add User Birthdays
  app/Http/Controllers/Admin/Users/UserController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/Users/AccountController.php
  app/Http/Middleware/CheckAlias.php
  app/Models/User/User.php
  app/Models/User/UserSettings.php
  app/Services/UserService.php
  database/migrations/2021_04_29_175640_add_user_birthday.php
  resources/views/account/settings.blade.php
  resources/views/admin/users/user.blade.php
  resources/views/auth/birthday.blade.php
  resources/views/auth/blocked.blade.php
  resources/views/auth/register.blade.php
  resources/views/user/profile.blade.php
  routes/lorekeeper/admin.php
  routes/lorekeeper/members.php
  routes/web.php
Labels: enhancement, reviewed
