Repository lk-arpg/lorekeeper, pull requests merged in 2021-09, with the labels that each got.

#146 chore: setup dependabot config
  .github/dependabot.yml
Labels: dependencies, reviewed

#145 fix(sales): 'is open' for chars even when only one
  resources/views/admin/sales/_character_select_entry.blade.php
Labels: reviewed

#144 docs: update readme for 2.0.0
  README.md
Labels: reviewed

#126 Fix for errored inventory addon forms not refilling the old data
  app/Services/CharacterManager.php
  app/Services/SubmissionManager.php
  app/Services/TradeManager.php
  resources/views/widgets/_inventory_select.blade.php
  resources/views/widgets/_inventory_select_js.blade.php
Labels: reviewed

#159 feat(raffles): improve ticket entry form
  app/Http/Controllers/Admin/RaffleController.php
  app/Models/Raffle/RaffleTicket.php
  app/Services/RaffleManager.php
  resources/views/admin/raffle/ticket_index.blade.php
Labels: enhancement, needs review

#167 fix variable and add log to rejecting submission
  app/Services/SubmissionManager.php
  app/Services/TradeManager.php
Labels: needs review

#168 fix: adds alt tags to images
  app/Models/Currency/Currency.php
  resources/views/account/bookmarks.blade.php
  resources/views/admin/files/images.blade.php
  resources/views/admin/masterlist/_transfer.blade.php
  resources/views/admin/masterlist/create_character.blade.php
  resources/views/admin/submissions/submission.blade.php
  resources/views/browse/_masterlist_content.blade.php
  resources/views/character/_inventory_stack.blade.php
  resources/views/character/_tab_images.blade.php
  resources/views/character/admin/_reupload_image_modal.blade.php
  resources/views/character/admin/upload_image.blade.php
  resources/views/character/character.blade.php
  resources/views/character/design/addons.blade.php
  resources/views/character/design/image.blade.php
  resources/views/character/images.blade.php
  resources/views/character/inventory.blade.php
  resources/views/character/myo/character.blade.php
  resources/views/character/profile.blade.php
  resources/views/galleries/_character.blade.php
  resources/views/galleries/create_edit_submission.blade.php
  resources/views/galleries/submission.blade.php
  resources/views/home/_character.blade.php
  resources/views/home/_inventory_stack.blade.php
  resources/views/home/_submission_content.blade.php
  resources/views/home/_transfer.blade.php
  resources/views/home/characters.blade.php
  resources/views/home/inventory.blade.php
  resources/views/home/myos.blade.php
  resources/views/home/trades/_offer.blade.php
  resources/views/home/trades/_offer_summary.blade.php
  resources/views/pages/_dashboard.blade.php
  resources/views/prompts/_entry.blade.php
  resources/views/prompts/_prompt_entry.blade.php
  resources/views/prompts/index.blade.php
  resources/views/sales/_character.blade.php
  resources/views/shops/_stock_modal.blade.php
  resources/views/shops/index.blade.php
  resources/views/shops/shop.blade.php
  resources/views/user/characters.blade.php
  resources/views/user/inventory.blade.php
  resources/views/user/myo_slots.blade.php
  resources/views/user/profile.blade.php
  resources/views/user/sublist.blade.php
  resources/views/widgets/_gallery_thumb.blade.php
  resources/views/widgets/_inventory_select.blade.php
  resources/views/widgets/_inventory_select_js.blade.php
  resources/views/widgets/_my_character_select.blade.php
  resources/views/world/_currency_entry.blade.php
  resources/views/world/_entry.blade.php
  resources/views/world/_feature_entry.blade.php
  resources/views/world/_item_category_entry.blade.php
  resources/views/world/_item_entry.blade.php
  resources/views/world/_prompt_entry.blade.php
  resources/views/world/_rarity_entry.blade.php
  resources/views/world/_species_entry.blade.php
  resources/views/world/_subtype_entry.blade.php
  resources/views/world/index.blade.php
  resources/views/world/item_page.blade.php
  resources/views/world/species_features.blade.php
Labels: needs review

#173 fix: 'invalid quantity' when attaching items
  resources/views/widgets/_inventory_select.blade.php
Labels: bug, reviewed

#169 Merge recaptcha (v3)
  app/Http/Controllers/Auth/RegisterController.php
  composer.json
  public/css/lorekeeper.css
  resources/lang/en/validation.php
  resources/views/auth/register.blade.php
  resources/views/layouts/app.blade.php
Labels: enhancement, reviewed

#175 fix: inventory filters, quantity error
  resources/views/widgets/_inventory_select.blade.php
  resources/views/widgets/_inventory_select_js.blade.php
Labels: bug, reviewed

#178 fix(characters): issue with .jpg files
  app/Models/Character/Character.php
  app/Models/Character/CharacterImage.php
Labels: bug, reviewed

#183 Add flex-wrap to pagination to keep it from breaking mobile view.
  .github/dependabot.yml
  public/css/lorekeeper.css
Labels: bug, reviewed
