Repository lk-arpg/lorekeeper, pull requests merged in 2021-05, with the labels that each got.

#94 Misc Fixes/Tweaks
  app/Http/Controllers/Characters/CharacterController.php
  app/Http/Controllers/ShopController.php
  app/Models/Character/CharacterProfile.php
  app/Models/User/User.php
  app/Services/ItemService.php
  resources/views/account/bookmarks.blade.php
  resources/views/character/_header.blade.php
  resources/views/shops/_stock_modal.blade.php
Labels: needs review

#88 Add item categories, rarity conditions to loot table options
  app/Http/Controllers/Admin/Data/LootTableController.php
  app/Models/Loot/Loot.php
  app/Models/Loot/LootTable.php
  app/Services/LootService.php
  config/lorekeeper/extensions.php
  database/migrations/2021_03_28_172111_add_item_category_info_to_loots.php
  resources/views/admin/items/create_edit_item.blade.php
  resources/views/admin/loot_tables/create_edit_loot_table.blade.php
Labels: enhancement, reviewed

#95 Add the ability to attach characters to sales posts
  app/Console/Commands/UpdateSalesComments.php
  app/Http/Controllers/Admin/SalesController.php
  app/Http/Controllers/Comments/CommentController.php
  app/Http/Controllers/SalesController.php
  app/Models/Sales/Sales.php
  app/Models/Sales/SalesCharacter.php
  app/Services/SalesService.php
  config/lorekeeper/settings.php
  database/migrations/2021_04_22_230225_create_sales_characters.php
  resources/views/admin/sales/_character_select.blade.php
  resources/views/admin/sales/_character_select_entry.blade.php
  resources/views/admin/sales/_character_select_js.blade.php
  resources/views/admin/sales/create_edit_sales.blade.php
  resources/views/sales/_character.blade.php
  resources/views/sales/_sales.blade.php
  routes/lorekeeper/admin.php
Labels: enhancement, javascript, needs review

#98 Edits to new Birthday functionality + User settings forms
  app/Http/Controllers/Admin/Users/UserController.php
  app/Models/User/User.php
  resources/views/account/settings.blade.php
  resources/views/admin/users/user.blade.php
  resources/views/user/profile.blade.php
Labels: needs review

#101 Fix processCharacters bug when creating sales
  app/Services/SalesService.php
Labels: reviewed

#102 Fix Setup-Amin-User command
  app/Console/Commands/SetupAdminUser.php
Labels: reviewed

#100 Feature/expand account authentication
  app/Console/Commands/UpdateAliasSiteNames.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/Users/AccountController.php
  app/Http/Controllers/Users/UserController.php
  app/Models/User/UserAlias.php
  app/Providers/EventServiceProvider.php
  app/Services/DeviantArtService.php
  app/Services/InventoryManager.php
  app/Services/LinkService.php
  composer.json
  config/lorekeeper/sites.php
  config/services.php
  resources/views/account/_hide_alias_modal.blade.php
  resources/views/account/_make_primary_modal.blade.php
  resources/views/account/_remove_alias_modal.blade.php
  resources/views/account/_sidebar.blade.php
  resources/views/account/aliases.blade.php
  resources/views/admin/users/user.blade.php
  resources/views/auth/link.blade.php
  resources/views/home.blade.php
  resources/views/user/_sidebar.blade.php
  resources/views/user/aliases.blade.php
  routes/lorekeeper/browse.php
  routes/lorekeeper/members.php
  routes/web.php
Labels: enhancement, reviewed

#105 Show deleted comments and children of deleted comments
  app/Http/Controllers/PermalinkController.php
  app/Models/Comment.php
  app/Traits/Commentable.php
  resources/views/comments/_comment.blade.php
  resources/views/comments/_perma_comments.blade.php
Labels: enhancement, needs review

#103 Opt out of FLoC
  resources/views/layouts/app.blade.php
Labels: reviewed

#109 Fix displaying uncategorized traits on characters attached to sales posts
  resources/views/sales/_character.blade.php
Labels: reviewed

#110 Fix creating/updating sales without characters
  app/Services/SalesService.php
Labels: reviewed

#111 Clean up commands going toward v2
  app/Console/Commands/FixChildCommentTypes.php
  app/Console/Commands/MigrateAliases.php
  app/Console/Commands/SetupAdminUser.php
  app/Console/Commands/UpdateAliasSiteNames.php
  app/Console/Commands/UpdateLorekeeperV2.php
  app/Console/Commands/UpdateSalesComments.php
Labels: reviewed

#112 doctrine/dbal fix and birthday fixes
  app/Console/Commands/SetupAdminUser.php
  app/Http/Controllers/Admin/Users/UserController.php
  app/Models/User/User.php
  composer.json
  database/migrations/2021_05_19_123518_change_birthday_column_type.php
  resources/views/admin/users/user.blade.php
Labels: reviewed

#115 Re-reduce dA request scope to only username
  app/Services/LinkService.php
Labels: reviewed

#119 fixing regex for discord
  app/Helpers/Helpers.php
  config/lorekeeper/sites.php
Labels: reviewed
