Repository lk-arpg/lorekeeper, pull requests merged in 2021-12, with the labels that each got.

#228 Tiny fix for the Tumblr alias
  app/Models/User/UserAlias.php
Labels: bug

#215 feature/clear myo image
  app/Http/Controllers/Admin/DesignController.php
  app/Services/CharacterManager.php
  app/Services/DesignUpdateManager.php
  config/lorekeeper/extensions.php
  resources/views/admin/designs/_approve_request_modal.blade.php
  resources/views/pages/credits.blade.php
Labels: enhancement, reviewed

#229 Seperates refreshing of subtype into a function
  resources/views/character/admin/_edit_features_modal.blade.php
Labels: reviewed
