Repository lk-arpg/lorekeeper, pull requests merged in 2022-05, with the labels that each got.

#309 Fixes Character Selection being unclear
  resources/views/admin/sales/_character_select_js.blade.php
  resources/views/galleries/_character_select_js.blade.php
  resources/views/js/_character_select_js.blade copy.php
  resources/views/js/_character_select_js.blade.php
Labels: reviewed, javascript

#310 Add the ability to generate the year in char codes
  config/lorekeeper/settings.php
  resources/views/widgets/_character_code_js.blade.php
Labels: enhancement, reviewed, javascript

#314 Bug:: Transfer log has errors if Character was Deleted
  resources/views/admin/masterlist/_transfer.blade.php
  resources/views/home/_transfer.blade.php
Labels: bug, reviewed

#312 Update to Laravel 9/PHP 8.1
  .github/workflows/format_php.yml
  .php-cs-fixer.dist.php
  app/Http/Controllers/Admin/Users/UserController.php
  app/Http/Controllers/BrowseController.php
  app/Http/Controllers/Users/InventoryController.php
  app/Http/Middleware/TrustProxies.php
  app/Models/Character/Character.php
  app/Models/Feature/Feature.php
  app/Models/Loot/LootTable.php
  app/Models/News.php
  app/Models/Sales/Sales.php
  app/Models/User/User.php
  app/Services/BookmarkManager.php
  app/Services/CharacterManager.php
  app/Services/DesignUpdateManager.php
  app/Services/GalleryManager.php
  app/Services/Item/SlotService.php
  app/Services/LootService.php
  app/Services/RankService.php
  app/Services/SalesService.php
  app/Services/SubmissionManager.php
  app/Services/TradeManager.php
  app/Services/UserService.php
  composer.json
  composer.lock
  config/feed.php
Labels: dependencies, reviewed
