Repository lk-arpg/lorekeeper, pull requests merged in 2022-07, with the labels that each got.

#336 User Profile Character/Sublist pages edited
  resources/views/user/characters.blade.php
  resources/views/user/sublist.blade.php
Labels: reviewed

#330 Bug:: Issue fix for ItemSlots not being usable
  app/Services/Service.php
Labels: bug, reviewed

#339 fix: stop exploit allowing currency duplication and add measures to e…
  app/Services/TradeManager.php
Labels: bug, reviewed

#341 Prompt permalinks
  app/Http/Controllers/PromptsController.php
  resources/views/prompts/_prompt_entry.blade.php
  resources/views/prompts/prompt.blade.php
  routes/lorekeeper/browse.php
Labels: enhancement, reviewed
