Repository lk-arpg/lorekeeper, pull requests merged in 2023-12, with the labels that each got.

#80 Two Factor Authentication
  app/Actions/Fortify/CreateNewUser.php
  app/Actions/Fortify/PasswordValidationRules.php
  app/Actions/Fortify/ResetUserPassword.php
  app/Actions/Fortify/UpdateUserPassword.php
  app/Actions/Fortify/UpdateUserProfileInformation.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Users/AccountController.php
  app/Models/User/User.php
  app/Providers/FortifyServiceProvider.php
  app/Providers/RouteServiceProvider.php
  app/Services/UserService.php
  composer.json
  composer.lock
  config/app.php
  config/fortify.php
  config/lorekeeper/extensions.php
  database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
  package-lock.json
  resources/views/account/settings.blade.php
  resources/views/auth/confirm_two_factor.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/confirm.blade.php
  resources/views/auth/passwords/forgot.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/two-factor-challenge.blade.php
  resources/views/auth/verify.blade.php
  resources/views/layouts/app.blade.php
  routes/fortify.php
  routes/lorekeeper/members.php
  routes/web.php
  yarn.lock
Labels: enhancement, reviewed

#744 Misc bugfixes/tweaks
  app/Console/Commands/CheckReleasedItems.php
  app/Helpers/HoneypotHandler.php
  app/Http/Controllers/Characters/CharacterController.php
  app/Models/Item/Item.php
  app/Services/InventoryManager.php
  config/honeypot.php
  resources/views/character/design/image.blade.php
Labels: bug, reviewed

#745 Allow Masterlist staff to see each others comments
  resources/views/character/design/_header.blade.php
Labels: bug, reviewed

#746 feature/laravel 10
  app/Models/Character/Character.php
  app/Models/Character/CharacterDesignUpdate.php
  app/Models/Character/CharacterFeature.php
  app/Models/Character/CharacterImage.php
  app/Models/Gallery/Gallery.php
  app/Models/News.php
  app/Models/Prompt/Prompt.php
  app/Models/Raffle/Raffle.php
  app/Models/Sales/Sales.php
  app/Models/User/User.php
  composer.json
  composer.lock
Labels: dependencies, reviewed

#747 fix(characters): update design update feature ordering
  app/Models/Character/CharacterDesignUpdate.php
Labels: bug, reviewed

#741 Feature/wysiwyg comments
  app/Http/Controllers/Comments/CommentController.php
  config/lorekeeper/settings.php
  resources/views/comments/_actions.blade.php
  resources/views/comments/_comment.blade.php
  resources/views/comments/_form.blade.php
  resources/views/comments/_perma_comments.blade.php
  resources/views/comments/_perma_layout.blade.php
  resources/views/comments/comments.blade.php
Labels: enhancement, reviewed

#743 Notify user of no reward
  app/Helpers/AssetHelpers.php
Labels: reviewed

#749 fix(images): Add hash and htaccess rule to prevent hidden images from being discoverable
  app/Console/Commands/AddImageHashes.php
  app/Models/Character/CharacterCategory.php
  app/Models/Character/CharacterDesignUpdate.php
  app/Models/Currency/Currency.php
  app/Models/Feature/Feature.php
  app/Models/Feature/FeatureCategory.php
  app/Models/Item/Item.php
  app/Models/Item/ItemCategory.php
  app/Models/Prompt/Prompt.php
  app/Models/Prompt/PromptCategory.php
  app/Models/Rarity.php
  app/Models/Shop/Shop.php
  app/Models/Species/Species.php
  app/Models/Species/Subtype.php
  app/Services/CharacterCategoryService.php
  app/Services/CurrencyService.php
  app/Services/FeatureService.php
  app/Services/ItemService.php
  app/Services/PromptService.php
  app/Services/RarityService.php
  app/Services/ShopService.php
  app/Services/SpeciesService.php
  composer.lock
  database/migrations/2023_12_11_190858_add_image_hash_to_images.php
Labels: enhancement, needs review

#750 Suggestion(sales): Comments anchor and consistency edit
  resources/views/sales/_sales.blade.php
  resources/views/sales/sales.blade.php
Labels: reviewed

#742 Feature/username changes
  app/Helpers/Helpers.php
  app/Http/Controllers/Users/AccountController.php
  app/Http/Controllers/Users/UserController.php
  app/Models/User/User.php
  app/Services/UserService.php
  config/lorekeeper/settings.php
  resources/views/account/settings.blade.php
  resources/views/comments/_actions.blade.php
  resources/views/user/_profile_content.blade.php
  resources/views/user/profile.blade.php
  routes/lorekeeper/members.php
Labels: enhancement, needs review

#756 fix(characters): Hide slug copy from MYO slots
  resources/views/character/_header.blade.php
Labels: bug, reviewed

#757 fix(user/usercontroller): redundant line, possible oversight
  app/Http/Controllers/Users/UserController.php
Labels: bug, reviewed

#759 fix(services): Minor comment errors
  app/Services/DesignUpdateManager.php
  app/Services/Item/BoxService.php
  app/Services/Item/SlotService.php
Labels: reviewed

#761 fix(commands): Extension Tracker not working on live due to backslash vs forwardslash
  app/Console/Commands/UpdateExtensionTracker.php
Labels: bug, reviewed

#762 fix(user): sidebar set_active fix
  resources/views/user/_sidebar.blade.php
Labels: bug, reviewed

#769 add-image-hashes command didn't convert currency icon images
  app/Console/Commands/AddImageHashes.php
  composer.lock
  package-lock.json
  package.json
  yarn.lock
Labels: bug, reviewed

#763 fix(user): Forced lowercase on name check
  resources/views/user/profile.blade.php
Labels: bug, reviewed

#764 fix(galleries): Shows subgalleries of parent while in subgallery (and siblings and avunculi!)
  app/Models/Gallery/Gallery.php
  resources/views/galleries/_sidebar.blade.php
Labels: bug, reviewed

#770 Bugfixes
  app/Actions/Fortify/CreateNewUser.php
  app/Console/Commands/FixRegisteredUsers.php
  app/Console/Commands/SetupAdminUser.php
  app/Http/Controllers/Admin/Users/UserController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/Users/AccountController.php
  app/Models/Feature/Feature.php
  app/Models/Gallery/Gallery.php
  app/Services/CharacterManager.php
  app/Services/UserService.php
  composer.json
  composer.lock
  resources/views/admin/submissions/submission.blade.php
  resources/views/admin/users/user.blade.php
  resources/views/auth/birthday.blade.php
Labels: bug, reviewed
