Repository lk-arpg/lorekeeper, pull requests merged in 2023-06, with the labels that each got.

#495 Feat: add usage of gravatar for user avatars
  app/Models/User/User.php
  config/lorekeeper/extensions.php
  resources/views/comments/_comment.blade.php
  resources/views/comments/_perma_comments.blade.php
  resources/views/galleries/submission.blade.php
  resources/views/pages/credits.blade.php
  resources/views/user/_profile_content.blade.php
  resources/views/user/profile.blade.php
Labels: enhancement, reviewed

#616 patch(credits): Added wiki links to my extensions missing them and re-alphabetized
  resources/views/pages/credits.blade.php
Labels: reviewed

#614 Feat(site): Modifying pagination to allow page select on ...
  app/Providers/AppServiceProvider.php
  public/css/lorekeeper.css
  resources/views/layouts/_pagination.blade.php
  resources/views/layouts/_pagination_js.blade.php
  resources/views/layouts/_simple-pagination.blade.php
  resources/views/layouts/app.blade.php
  resources/views/pages/credits.blade.php
Labels: enhancement, needs review

#621 fix: prevent caching on design updates
  resources/views/character/design/image.blade.php
Labels: bug, reviewed

#631 Feat(Species Trait Index): Adds modals when clicking on traits
  app/Http/Controllers/WorldController.php
  config/lorekeeper/extensions.php
  resources/views/pages/credits.blade.php
  resources/views/world/_species_entry.blade.php
  resources/views/world/species_features.blade.php
  routes/lorekeeper/browse.php
Labels: enhancement, reviewed

#632 Bug(Design Submission): Duplicated Credits & Saving Credits w/o image
  app/Services/DesignUpdateManager.php
  resources/views/character/design/image.blade.php
Labels: bug, reviewed

#633 Bug(AliasLogin): Add email and pw after alias registration
  app/Http/Controllers/Users/AccountController.php
Labels: bug, reviewed
