Repository lk-arpg/lorekeeper, pull requests merged in 2023-03, with the labels that each got.

#555 Adjust Prev and Next Buttons to respect when 'character_pull_number' is 'all',
  app/Http/Controllers/Characters/CharacterController.php
Labels: bug, needs review

#556 Feat(character): Updating previous and next buttons to skip the gaps
  app/Http/Controllers/Characters/CharacterController.php
  config/lorekeeper/extensions.php
  resources/views/character/_header.blade.php
Labels: enhancement, needs review

#522 add optional aliases
  app/Http/Middleware/CheckAlias.php
  app/Models/User/User.php
  app/Services/LinkService.php
  config/lorekeeper/settings.php
  resources/views/account/aliases.blade.php
Labels: enhancement, needs review

#535 PHP 8.1 upgrade
  composer.json
Labels: dependencies, reviewed
