Repository lk-arpg/lorekeeper, pull requests merged in 2023-04, with the labels that each got.

#582 make it so css auto updates
  resources/views/layouts/app.blade.php
Labels: reviewed

#584 bug(credits): incorrect variable name, would display always as disabled
  resources/views/pages/credits.blade.php
Labels: bug, reviewed

#583 feat(user): Added aliases on userprofile feature
  app/Http/Controllers/Users/UserController.php
  config/lorekeeper/extensions.php
  resources/views/pages/credits.blade.php
  resources/views/user/_profile_content.blade.php
Labels: enhancement, reviewed

#585 fix(inventories): fix for user, home and character inventories
  resources/views/character/inventory.blade.php
  resources/views/home/inventory.blade.php
  resources/views/user/inventory.blade.php
Labels: bug, reviewed
