Repository lk-arpg/lorekeeper, pull requests merged in 2023-08, with the labels that each got.

#644 Update AuthServiceProvider.php
  app/Policies/CommentPolicy.php
  app/Providers/AuthServiceProvider.php
  resources/views/admin/reports/report.blade.php
Labels: reviewed

#645 Fix(world): Wrong entry type for rarity
  resources/views/admin/rarities/create_edit_rarity.blade.php
Labels: bug, reviewed

#662 Bug(Settings): Fix .gif Avatars causing 500 error
  app/Services/UserService.php
  resources/views/account/settings.blade.php
Labels: bug, reviewed

#669 New Feature: Adds a page that shows the Full Inventory
  app/Http/Controllers/Users/InventoryController.php
  resources/views/home/inventory.blade.php
  resources/views/home/inventory_full.blade.php
  routes/lorekeeper/members.php
Labels: enhancement, reviewed

#676 Bug(Shops): Shops with no image will show broken image icon
  resources/views/shops/shop.blade.php
Labels: bug, reviewed
