Repository lk-arpg/lorekeeper, pull requests merged in 2023-01, with the labels that each got.

#475 feat(species): add visibility toggle
  app/Http/Controllers/Admin/Data/SpeciesController.php
  app/Http/Controllers/BrowseController.php
  app/Http/Controllers/Characters/DesignController.php
  app/Http/Controllers/WorldController.php
  app/Models/Species/Species.php
  app/Services/SpeciesService.php
  database/migrations/2022_12_22_205505_add_is_visible_to_specieses.php
  resources/views/admin/specieses/create_edit_species.blade.php
Labels: enhancement, reviewed

#491 Update comments as requested for next major release
  app/Console/Commands/SetupAdminUser.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Characters/CharacterController.php
  app/Http/Controllers/Comments/CommentController.php
  app/Http/Controllers/Comments/CommentControllerInterface.php
  app/Http/Controllers/PermalinkController.php
  app/Models/Gallery/GallerySubmission.php
  app/Models/Sales/SalesCharacter.php
  app/Models/Species/Species.php
  app/Policies/CommentPolicy.php
  app/Providers/EventServiceProvider.php
  app/Services/CharacterManager.php
  app/Services/DesignUpdateManager.php
  config/app.php
  config/auth.php
  config/broadcasting.php
  config/cache.php
  config/database.php
  config/feed.php
  config/filesystems.php
  config/hashing.php
  config/logging.php
  config/lorekeeper/admin_sidebar.php
  config/lorekeeper/allowed_comment_models.php
  config/lorekeeper/comments.php
  config/lorekeeper/ext-tracker/extension_tracker.php
  config/lorekeeper/extensions.php
  config/lorekeeper/group_currency_form.php
  config/lorekeeper/image_files.php
  config/lorekeeper/item_tags.php
  config/lorekeeper/notifications.php
  config/lorekeeper/powers.php
  config/lorekeeper/settings.php
  config/lorekeeper/sites.php
  config/lorekeeper/text_pages.php
  config/mail.php
  config/queue.php
  config/services.php
  config/session.php
  config/view.php
  resources/lang/en/validation.php
  resources/views/comments/_actions.blade.php
  resources/views/comments/_comment.blade.php
  resources/views/comments/_form.blade.php
  resources/views/comments/_perma_comments.blade.php
  routes/lorekeeper/members.php
Labels: reviewed

#494 Update _profile_content.blade.php
  resources/views/user/_profile_content.blade.php
Labels: reviewed

#496 fix: Search Traits by Category cancelling out after each search
  resources/views/world/features.blade.php
Labels: reviewed

#497 feat(world): search and sort traits by subtype
  app/Http/Controllers/Admin/Data/SpeciesController.php
  app/Http/Controllers/BrowseController.php
  app/Http/Controllers/Characters/DesignController.php
  app/Http/Controllers/WorldController.php
  app/Models/Feature/Feature.php
  app/Models/Species/Subtype.php
  database/migrations/2023_01_13_175257_add_is_visible_to_subtypes.php
  resources/views/admin/specieses/create_edit_subtype.blade.php
  resources/views/world/features.blade.php
Labels: enhancement, reviewed

#499 feat(watermark): Watermark Resizing
  app/Services/CharacterManager.php
  config/lorekeeper/settings.php
  resources/views/pages/credits.blade.php
Labels: enhancement, reviewed

#509 fix(deactivation): Function doesn't exist, fixed
  app/Services/UserService.php
Labels: reviewed

#492 fix: missing use statement for Facades/View
  app/Http/Controllers/NewsController.php
  app/Http/Controllers/SalesController.php
Labels: reviewed

#511 Bug(Comments): Users able to feature comments they shouldn't
  resources/views/comments/_actions.blade.php
Labels: bug, needs review

#519 Fix:(browse): Misplaced hr tag
  resources/views/browse/_masterlist_content.blade.php
Labels: reviewed
