Repository lk-arpg/lorekeeper, pull requests merged in 2023-05, with the labels that each got.

#593 fix(galleries): Sidebar now shows active galleries + fix:(version) updated to 3.0.0
  app/Console/Kernel.php
  app/Http/Controllers/Users/BookmarkController.php
  app/Http/Controllers/Users/TradeController.php
  app/Models/Submission/Submission.php
  app/Providers/RouteServiceProvider.php
  app/Services/InventoryManager.php
  config/lorekeeper/settings.php
  resources/views/galleries/_sidebar.blade.php
Labels: bug, needs review

#594 feat(gallery): Show All Recent Submissions
  app/Http/Controllers/GalleryController.php
  app/Http/Controllers/HomeController.php
  config/lorekeeper/extensions.php
  resources/views/galleries/_sidebar.blade.php
  resources/views/galleries/index.blade.php
  resources/views/galleries/showall.blade.php
  resources/views/pages/_dashboard.blade.php
  resources/views/pages/credits.blade.php
  resources/views/widgets/_recent_gallery_submissions.blade.php
  routes/lorekeeper/browse.php
Labels: enhancement, reviewed

#569 bug(items): item images weren't deleting
  app/Services/ItemService.php
Labels: bug, reviewed

#598 patch(features): Putting the Add Trait button ABOVE the trait list
  resources/views/admin/masterlist/create_character.blade.php
  resources/views/character/admin/_edit_features_modal.blade.php
  resources/views/character/admin/upload_image.blade.php
  resources/views/character/design/features.blade.php
Labels: reviewed

#600 Marks off items, traits, species and species subtypes as not-visible in admin lists.
  resources/views/admin/features/features.blade.php
  resources/views/admin/items/items.blade.php
  resources/views/admin/specieses/specieses.blade.php
  resources/views/admin/specieses/subtypes.blade.php
Labels: enhancement, reviewed

#601 patch(sales): Allows hidden characters to be added to sales.
  app/Http/Controllers/Admin/SalesController.php
  app/Services/SalesService.php
  resources/views/home/_character.blade.php
Labels: enhancement, reviewed

#602 fix(browse): Apparently this is supposed to be in here.
  app/Http/Controllers/BrowseController.php
Labels: bug, reviewed

#523 hotfix: Fixing error with lowercase "auth"
  app/Policies/CommentPolicy.php
  resources/views/admin/reports/report.blade.php
Labels: bug, reviewed

#612 Update _sidebar.blade.php
  config/lorekeeper/extensions.php
  resources/views/admin/_sidebar.blade.php
Labels: enhancement, reviewed

#493 Adds Alias Login's to Develop
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Models/User/User.php
  app/Models/User/UserAlias.php
  app/Providers/EventServiceProvider.php
  app/Providers/Socialite/ToyhouseProvider.php
  app/Services/LinkService.php
  app/Services/UserService.php
  composer.json
  config/lorekeeper/sites.php
  config/services.php
  database/migrations/2022_12_15_000150_add_extra_data_to_user_aliases.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/register_with_driver.blade.php
  routes/web.php
Labels: enhancement, needs review

#613 add searching to admin logs
  app/Http/Controllers/Admin/HomeController.php
  resources/views/admin/logs.blade.php
Labels: enhancement, reviewed
