Repository lk-arpg/lorekeeper, pull requests merged in 2023-11, with the labels that each got.

#700 Fix item pages in worldcontroller
  app/Http/Controllers/WorldController.php
Labels: bug, reviewed

#715 make character input fields select instead of text
  app/Http/Controllers/Admin/SubmissionController.php
  resources/views/admin/sales/_character_select.blade.php
  resources/views/admin/sales/_character_select_entry.blade.php
  resources/views/admin/sales/_character_select_js.blade.php
  resources/views/admin/submissions/submission.blade.php
  resources/views/galleries/_character_select.blade.php
  resources/views/galleries/_character_select_entry.blade.php
  resources/views/galleries/_character_select_js.blade.php
  resources/views/js/_character_select_js.blade.php
  resources/views/widgets/_character_select.blade.php
  resources/views/widgets/_character_select_entry.blade.php
Labels: enhancement, reviewed

#727 fix(mobile): Various mobile improvements
  public/css/lorekeeper.css
  resources/views/browse/_masterlist_content.blade.php
  resources/views/character/profile.blade.php
  resources/views/user/_profile_content.blade.php
Labels: reviewed

#668 add utility reward string creation
  app/Helpers/AssetHelpers.php
  app/Services/Item/BoxService.php
Labels: enhancement, reviewed
