Repository lk-arpg/lorekeeper, pull requests merged in 2024-08, with the labels that each got.

#1013 Fix Gallery Performance
  package-lock.json
  resources/views/galleries/index.blade.php
Labels: bug, reviewed

#1015 Fix error on invalid submission
  package-lock.json
  resources/views/widgets/_inventory_select.blade.php
Labels: bug, reviewed

#1014 Fix Permalinks sometimes 404'ing incorrectly
  app/Http/Controllers/PermalinkController.php
  package-lock.json
Labels: bug, reviewed

#1019 feat: make comment links become clickable to prevent weird views
  app/Models/Comment/Comment.php
Labels: enhancement, reviewed

#1020 Fix: Visual Trait Index image resizing on view
  resources/views/world/species_features.blade.php
Labels: bug, reviewed

#1021 Feature/comment sorting
  app/Http/Controllers/Comments/CommentController.php
  app/Http/Controllers/PermalinkController.php
  app/Models/Comment/Comment.php
  resources/views/comments/_comments.blade.php
  resources/views/comments/comments.blade.php
  resources/views/comments/permalink_comment.blade.php
  routes/lorekeeper/browse.php
  routes/lorekeeper/members.php
Labels: enhancement, reviewed

#1022 Add Log Viewer Ext. to Develop
  app/Http/Controllers/Admin/LogController.php
  config/lorekeeper/admin_sidebar.php
  resources/views/admin/logs/index.blade.php
  resources/views/admin/logs/log.blade.php
  routes/lorekeeper/admin.php
Labels: enhancement, reviewed

#1027 Bug(Comments): Permalinks pull all comments into memory
  app/Http/Controllers/PermalinkController.php
  package-lock.json
Labels: bug, reviewed

#1031 chore(deps-dev): set up mix, rebuild assets
  .github/workflows/CI.yml
  package-lock.json
  package.json
  public/css/app.css
  public/js/app-secondary.js
  public/js/app-secondary.js.LICENSE.txt
  public/js/app.js
  public/js/app.js.LICENSE.txt
  public/js/jquery-ui.min.js
  public/js/lightbox.min.js
  public/mix-manifest.json
  resources/js/app-secondary.js
  resources/js/app.js
  resources/js/bootstrap4-toggle.js
  resources/js/jquery-ui.js
  resources/js/lightbox.js
  resources/js/selectize.js
  resources/sass/app.scss
  resources/views/browse/_masterlist_content.blade.php
  resources/views/layouts/app.blade.php
  webpack.mix.js
  yarn.lock
Labels: dependencies, reviewed

#1026 Fix(admin): Admin Area Bootstrap tables (non-sortables)
  resources/views/admin/files/index.blade.php
  resources/views/admin/logs.blade.php
  resources/views/admin/loot_tables/_roll_loot_table.blade.php
  resources/views/admin/raffle/ticket_index.blade.php
  resources/views/admin/sales/sales.blade.php
  resources/views/admin/settings/settings.blade.php
  resources/views/admin/staff_reward_settings.blade.php
  resources/views/admin/users/user_update_log.blade.php
Labels: bug, reviewed

#1033 fix(comments): stop url parsing on wysiwyg images
  app/Models/Comment/Comment.php
Labels: bug, reviewed

#959 Fix: Character Image Size Validation
  app/Http/Controllers/Admin/Characters/CharacterImageController.php
  app/Models/Character/Character.php
  app/Models/Character/CharacterImage.php
Labels: bug, reviewed

#870 Extension/multiple subtypes
  app/Console/Commands/ConvertCharacterSubtype.php
  app/Http/Controllers/Admin/Characters/CharacterController.php
  app/Http/Controllers/Admin/Characters/CharacterImageController.php
  app/Http/Controllers/Admin/Data/ItemController.php
  app/Http/Controllers/BrowseController.php
  app/Http/Controllers/Characters/DesignController.php
  app/Models/Character/CharacterDesignUpdate.php
  app/Models/Character/CharacterImage.php
  app/Models/Character/CharacterImageSubtype.php
  app/Models/Item/ItemTag.php
  app/Models/Species/Subtype.php
  app/Services/CharacterManager.php
  app/Services/DesignUpdateManager.php
  app/Services/Item/SlotService.php
  app/Services/SpeciesService.php
  composer.lock
  config/lorekeeper/extensions.php
  database/migrations/2024_08_28_103434_convert_character_subtypes.php
  resources/views/admin/items/tags/slot.blade.php
  resources/views/admin/masterlist/_create_character_subtype.blade.php
  resources/views/admin/masterlist/create_character.blade.php
  resources/views/browse/_masterlist_content.blade.php
  resources/views/character/_image_info.blade.php
  resources/views/character/admin/_edit_features_modal.blade.php
  resources/views/character/admin/_edit_features_subtype.blade.php
  resources/views/character/admin/_upload_image_subtype.blade.php
  resources/views/character/admin/upload_image.blade.php
  resources/views/character/design/features.blade.php
  resources/views/inventory/_slot.blade.php
Labels: enhancement, reviewed

#1036 fix(character manager): HandleCharacterImage function consistency
  app/Services/CharacterManager.php
Labels: bug, reviewed

#1037 Fix multiple comment display & loading, multiple subtypes command
  app/Console/Commands/ConvertCharacterSubtype.php
  resources/views/comments/_comments.blade.php
  resources/views/comments/comments.blade.php
  resources/views/galleries/submission_log.blade.php
Labels: bug, reviewed

#1034 fix(sales/news): Removed redundant anchor, fixed links and consistency
  resources/views/news/_news.blade.php
  resources/views/news/news.blade.php
  resources/views/sales/_sales.blade.php
  resources/views/sales/sales.blade.php
Labels: reviewed
