Repository lk-arpg/lorekeeper, pull requests merged in 2024-06, with the labels that each got.

#967 Fix: Optimalizations and redundancy removal
  app/Http/Controllers/WorldController.php
  config/lorekeeper/extensions.php
  resources/views/admin/currencies/create_edit_currency.blade.php
  resources/views/admin/features/create_edit_feature.blade.php
  resources/views/admin/galleries/create_edit_gallery.blade.php
  resources/views/admin/grants/user_currency.blade.php
  resources/views/admin/items/create_edit_item.blade.php
  resources/views/admin/masterlist/create_character.blade.php
  resources/views/admin/news/create_edit_news.blade.php
  resources/views/admin/pages/create_edit_page.blade.php
  resources/views/admin/prompts/create_edit_prompt.blade.php
  resources/views/admin/sales/create_edit_sales.blade.php
  resources/views/admin/shops/_stock.blade.php
  resources/views/admin/sublist/create_edit_sublist.blade.php
  resources/views/admin/users/_create_edit_rank.blade.php
  resources/views/prompts/_prompt_entry.blade.php
  resources/views/user/_characters.blade.php
  resources/views/user/character_designs.blade.php
  resources/views/user/characters.blade.php
  resources/views/user/myo_slots.blade.php
  resources/views/user/sublist.blade.php
  resources/views/world/_sidebar.blade.php
  resources/views/world/_species_entry.blade.php
  resources/views/world/index.blade.php
  resources/views/world/species_features.blade.php
  resources/views/world/universal_features.blade.php
  routes/lorekeeper/browse.php
Labels: reviewed

#971 Fix: Remove old fa-close line from character selection
  resources/views/admin/sales/_character_select.blade.php
  resources/views/admin/sales/_character_select_entry.blade.php
  resources/views/admin/submissions/submission.blade.php
  resources/views/galleries/_character_select.blade.php
  resources/views/galleries/_character_select_entry.blade.php
  resources/views/widgets/_character_select.blade.php
  resources/views/widgets/_character_select_entry.blade.php
Labels: bug, reviewed

#970 feat(world): Subtype Trait Index and code condensation
  app/Http/Controllers/WorldController.php
  app/Models/Species/Subtype.php
  config/lorekeeper/extensions.php
  resources/views/world/_features_index.blade.php
  resources/views/world/_features_index_modal_js.blade.php
  resources/views/world/_subtype_entry.blade.php
  resources/views/world/species_features.blade.php
  resources/views/world/subtype_features.blade.php
  resources/views/world/universal_features.blade.php
  routes/lorekeeper/browse.php
Labels: enhancement, reviewed

#973 fix(characters): wrong div class in extended mentions
  resources/views/character/_image_info.blade.php
Labels: bug, reviewed

#976 Add numeric check to parse to prevent dropdowns from being parsed
  app/Http/Middleware/ParsePostRequestFields.php
  config/lorekeeper/settings.php
Labels: bug, reviewed

#987 Small shop bug fixes
  resources/views/shops/_stock_modal.blade.php
  resources/views/shops/shop.blade.php
Labels: bug, reviewed
