Repository lk-arpg/lorekeeper, pull requests merged in 2024-01, with the labels that each got.

#779 Make back-hashing images optional
  app/Console/Commands/UpdateLorekeeperV3.php
Labels: reviewed

#780 fix(user): FTO badge unreasonably small
  resources/views/user/_profile_content.blade.php
Labels: reviewed

#781 suggestion(character): Sale value switch gets removed
  resources/views/character/_tab_stats.blade.php
  resources/views/character/admin/_edit_stats_modal.blade.php
Labels: reviewed

#782 fix(characters): default to png for myo image if image format not set
  app/Services/CharacterManager.php
Labels: bug, reviewed

#789 feature/design update addon fix
  resources/views/character/design/addons.blade.php
Labels: bug, reviewed

#790 Allow for removal of last power on a rank
  app/Services/RankService.php
Labels: bug, reviewed

#783 Suggestion: species visual index fix
  resources/views/world/species_features.blade.php
Labels: reviewed

#771 Datetimepicker consistency fix, widget creation, localization and nitpicks
  public/css/lorekeeper.css
  resources/views/admin/designs/_approve_request_modal.blade.php
  resources/views/admin/galleries/create_edit_gallery.blade.php
  resources/views/admin/masterlist/create_character.blade.php
  resources/views/admin/news/create_edit_news.blade.php
  resources/views/admin/prompts/create_edit_prompt.blade.php
  resources/views/admin/sales/create_edit_sales.blade.php
  resources/views/character/admin/_edit_stats_modal.blade.php
  resources/views/widgets/_character_create_options_js.blade.php
  resources/views/widgets/_datetimepicker_js.blade.php
Labels: bug, reviewed

#792 feature/password reset fix
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/forgot.blade.php
  resources/views/auth/passwords/reset.blade.php
Labels: bug, reviewed

#793 Bug(Thumbnails): Add Imagick switch to thumbnails
  app/Services/CharacterManager.php
Labels: bug, reviewed

#804 hotfix: Allow admins to recrop thumbnails in Design Update Requests
  app/Services/DesignUpdateManager.php
Labels: bug, reviewed

#803 fix(characters): MYO image format, thumbnail webp support fixes
  app/Services/CharacterManager.php
Labels: bug, reviewed

#795 fix(admin/traits): This will automatically restrict subtypes for the creation/editing of traits
  app/Http/Controllers/Admin/Data/FeatureController.php
  resources/views/admin/features/_create_edit_feature_subtype.blade.php
  resources/views/admin/features/create_edit_feature.blade.php
  routes/lorekeeper/admin.php
Labels: bug, reviewed

#794 Universal trait index merged into core
  app/Http/Controllers/WorldController.php
  config/lorekeeper/extensions.php
  resources/views/pages/credits.blade.php
  resources/views/world/_sidebar.blade.php
  resources/views/world/index.blade.php
  resources/views/world/universal_features.blade.php
  routes/lorekeeper/browse.php
Labels: enhancement, reviewed

#813 Prevent Horizontal Stretch on <main>
  public/css/lorekeeper.css
Labels: bug, reviewed

#817 Bug(Reports): User's couldn't see comments of assigned tickets
  resources/views/home/_report_content.blade.php
Labels: bug, reviewed
