Repository lk-arpg/lorekeeper, pull requests merged in 2024-02, with the labels that each got.

#823 Bug(Prompts): Image hash not saving
  app/Services/PromptService.php
Labels: bug, reviewed

#824 Bug(Visual Trait Index): Hidden Traits were still showing when they shouldn't
  app/Models/Feature/Feature.php
Labels: bug, reviewed

#825 Fix/masterlist myo sort and cleanup
  app/Http/Controllers/BrowseController.php
  resources/views/browse/_masterlist_content.blade.php
Labels: bug, reviewed

#828 fix: add back has_image checks and also change honeypot to return for better UX
  app/Helpers/HoneypotHandler.php
  resources/views/shops/index.blade.php
  resources/views/user/inventory.blade.php
Labels: bug, reviewed

#827 Feature/currency conversion
  app/Http/Controllers/Admin/Data/CurrencyController.php
  app/Http/Controllers/Users/BankController.php
  app/Models/Currency/Currency.php
  app/Models/Currency/CurrencyConversion.php
  app/Services/CurrencyManager.php
  app/Services/CurrencyService.php
  database/migrations/2024_02_09_104441_create_currency_conversion_tables.php
  resources/views/admin/currencies/create_edit_currency.blade.php
  resources/views/home/_bank_convert.blade.php
  resources/views/home/bank.blade.php
  resources/views/world/_currency_entry.blade.php
  routes/lorekeeper/members.php
Labels: enhancement, reviewed

#834 fix(users): clean up UserService
  app/Services/UserService.php
Labels: bug, reviewed

#833 fix(shops): validate quantity against purchase limit
  app/Services/ShopManager.php
  config/lorekeeper/settings.php
Labels: bug, reviewed

#836 fix: convert remaining dates to casts
  app/Models/Raffle/RaffleTicket.php
  app/Models/User/UserSettings.php
Labels: bug, reviewed

#835 Bug(Images): Old Fullsize images no longer detected
  app/Models/Character/CharacterImage.php
Labels: bug, reviewed

#758 chore(workflows): consolidate linting, use reusable workflows
  .github/workflows/Lint.yml
  .github/workflows/format_blade.yml
  .github/workflows/format_php.yml
Labels: reviewed

#844 feat(admin/features): Sorting traits in admin
  app/Http/Controllers/Admin/Data/FeatureController.php
  resources/views/admin/features/features.blade.php
Labels: enhancement, reviewed

#848 Fix(admin/traits:) Adding "without" filter options
  .github/workflows/Lint.yml
  .github/workflows/format_blade.yml
  .github/workflows/format_php.yml
  app/Http/Controllers/Admin/Data/FeatureController.php
  app/Models/Character/CharacterImage.php
  app/Models/Raffle/RaffleTicket.php
  app/Models/User/UserSettings.php
  resources/views/auth/register_with_driver.blade.php
Labels: enhancement, reviewed

#849 feat(shops): Add shop image to meta-img, if it exists
  resources/views/shops/shop.blade.php
Labels: enhancement, reviewed

#850 fix(titles): A lot of layout title fixes
  resources/views/admin/characters/create_edit_character_category.blade.php
  resources/views/admin/currencies/create_edit_currency.blade.php
  resources/views/admin/features/create_edit_feature.blade.php
  resources/views/admin/features/create_edit_feature_category.blade.php
  resources/views/admin/galleries/create_edit_gallery.blade.php
  resources/views/admin/items/create_edit_item.blade.php
  resources/views/admin/items/create_edit_item_category.blade.php
  resources/views/admin/loot_tables/create_edit_loot_table.blade.php
  resources/views/admin/news/create_edit_news.blade.php
  resources/views/admin/pages/create_edit_page.blade.php
  resources/views/admin/prompts/create_edit_prompt.blade.php
  resources/views/admin/prompts/create_edit_prompt_category.blade.php
  resources/views/admin/rarities/create_edit_rarity.blade.php
  resources/views/admin/sales/create_edit_sales.blade.php
  resources/views/admin/shops/create_edit_shop.blade.php
  resources/views/admin/specieses/create_edit_species.blade.php
  resources/views/admin/specieses/create_edit_subtype.blade.php
  resources/views/admin/specieses/subtypes.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/admin/users/user.blade.php
  resources/views/admin/users/user_ban.blade.php
  resources/views/admin/users/user_deactivate.blade.php
  resources/views/admin/users/user_update_log.blade.php
  resources/views/character/design/addons.blade.php
  resources/views/character/design/comments.blade.php
  resources/views/character/design/features.blade.php
  resources/views/character/design/image.blade.php
  resources/views/character/design/index.blade.php
  resources/views/character/design/layout.blade.php
  resources/views/character/design/request.blade.php
  resources/views/character/layout.blade.php
  resources/views/prompts/index.blade.php
  resources/views/prompts/prompt.blade.php
  resources/views/prompts/prompt_categories.blade.php
  resources/views/prompts/prompts.blade.php
  resources/views/world/character_categories.blade.php
  resources/views/world/currencies.blade.php
  resources/views/world/feature_categories.blade.php
  resources/views/world/features.blade.php
  resources/views/world/index.blade.php
  resources/views/world/item_categories.blade.php
  resources/views/world/item_page.blade.php
  resources/views/world/items.blade.php
  resources/views/world/rarities.blade.php
  resources/views/world/species_features.blade.php
  resources/views/world/specieses.blade.php
  resources/views/world/subtypes.blade.php
Labels: bug, reviewed

#852 fix(ranks): Clicking any label went to 'Edit World Data' only...
  resources/views/admin/users/_create_edit_rank.blade.php
Labels: bug, reviewed

#854 fix(many): @comments overwriting scripts section
  resources/views/comments/comments.blade.php
Labels: bug, reviewed

#853 fix(reports): Somehow the comment type was missing?
  resources/views/admin/reports/report.blade.php
  resources/views/home/_report_content.blade.php
Labels: bug, reviewed

#857 optimize(reports): Minor optimization towards reports
  resources/views/admin/reports/report.blade.php
Labels: reviewed
