Repository lk-arpg/lorekeeper, pull requests merged in 2024-10, with the labels that each got.

#1064 Add Extra / Nice-To-Have Filters
  app/Http/Controllers/Admin/Data/ItemController.php
  app/Http/Controllers/Admin/Data/LootTableController.php
  app/Http/Controllers/Characters/CharacterController.php
  app/Http/Controllers/Users/InventoryController.php
  app/Http/Controllers/Users/UserController.php
  app/Http/Controllers/WorldController.php
  app/Models/User/User.php
  resources/views/admin/items/items.blade.php
  resources/views/admin/loot_tables/loot_tables.blade.php
  resources/views/character/inventory.blade.php
  resources/views/home/inventory.blade.php
  resources/views/user/inventory.blade.php
  resources/views/user/submission_logs.blade.php
  resources/views/world/items.blade.php
Labels: enhancement, reviewed

#1082 hotfix: Fix visibility issues for gallery submissions
  app/Http/Controllers/Characters/CharacterController.php
  app/Http/Controllers/Users/UserController.php
  app/Models/User/User.php
Labels: bug, reviewed

#1093 Bug(DesignManager): $subtype doesn't exist if unspecified
  app/Services/DesignUpdateManager.php
  package-lock.json
Labels: bug, reviewed

#1099 style: making some rows look nicer
  resources/views/character/_image_info.blade.php
  resources/views/character/_tab_stats.blade.php
  resources/views/user/_profile_content.blade.php
Labels: reviewed

#1098 fix(galleries): more efficient queries
  app/Http/Controllers/GalleryController.php
  resources/views/galleries/gallery.blade.php
Labels: needs review
