Repository lk-arpg/lorekeeper, pull requests merged in 2024-04, with the labels that each got.

#897 fix(maintenance): Errored out on non-users during maintenance
  resources/views/layouts/app.blade.php
Labels: bug, reviewed

#899 fix(admin):consistency fix
  resources/views/admin/items/items.blade.php
Labels: bug, reviewed

#908 Optimization(all): Auth::user() optimization
  app/Http/Controllers/Admin/SubmissionController.php
  app/Http/Controllers/BrowseController.php
  app/Http/Controllers/Characters/CharacterController.php
  app/Http/Controllers/Characters/DesignController.php
  app/Http/Controllers/GalleryController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/PromptsController.php
  app/Http/Controllers/ShopController.php
  app/Http/Controllers/Users/InventoryController.php
  app/Http/Controllers/Users/ReportController.php
  app/Http/Controllers/Users/SubmissionController.php
  app/Http/Controllers/Users/TradeController.php
  app/Http/Controllers/Users/UserController.php
  app/Http/Controllers/WorldController.php
  resources/views/admin/sales/_character_select.blade.php
  resources/views/admin/sales/_character_select_entry.blade.php
  resources/views/character/character.blade.php
  resources/views/character/images.blade.php
  resources/views/character/profile.blade.php
  resources/views/galleries/_character_select.blade.php
  resources/views/galleries/_character_select_entry.blade.php
  resources/views/widgets/_character_select.blade.php
  resources/views/widgets/_character_select_entry.blade.php
Labels: reviewed

#913 fix(world): Items and traits duplication issue on encyclopedia
  app/Http/Controllers/WorldController.php
Labels: bug, reviewed

#915 Designs page
  app/Http/Controllers/Users/UserController.php
  app/Models/User/User.php
  resources/views/user/_sidebar.blade.php
  resources/views/user/character_designs.blade.php
  routes/lorekeeper/browse.php
Labels: enhancement, reviewed

#923 fix(claims): userGallerySubmissions 500'd claims
  app/Http/Controllers/Users/SubmissionController.php
Labels: bug, reviewed

#924 fix(world): Staff without edit_data should not be able to see items
  app/Http/Controllers/WorldController.php
  app/Models/Item/Item.php
Labels: reviewed

#925 fix(admin): Hide Gallery Queues for those who have no access
  resources/views/admin/index.blade.php
Labels: bug, reviewed

#892 Add site icons to off-site users
  app/Helpers/Helpers.php
  config/lorekeeper/sites.php
Labels: enhancement, reviewed
