Repository lk-arpg/lorekeeper, pull requests merged in 2024-03, with the labels that each got.

#847 add optional gallery submissions on prompts
  app/Http/Controllers/Users/SubmissionController.php
  app/Models/Submission/Submission.php
  app/Services/SubmissionManager.php
  config/lorekeeper/settings.php
  resources/views/admin/submissions/submission.blade.php
  resources/views/home/_submission_content.blade.php
  resources/views/home/_submission_form.blade.php
  resources/views/home/create_submission.blade.php
  resources/views/home/edit_submission.blade.php
Labels: enhancement, reviewed

#874 fix(world): Unhide hidden categories for appropriate staff on Universal Visual Index
  resources/views/world/universal_features.blade.php
Labels: bug, reviewed

#873 fix(world): Unhide hidden categories for appropriate staff on Species Visual Index
  resources/views/world/species_features.blade.php
Labels: bug, reviewed

#889 Fix(credits): Missing wikilinks and abbreviated names
  resources/views/pages/credits.blade.php
Labels: reviewed

#891 Bug(Admin): New Powers didn't give sidebar access
  config/lorekeeper/admin_sidebar.php
Labels: bug, reviewed
