Repository lk-arpg/lorekeeper, pull requests merged in 2024-11, with the labels that each got.

#1105 fix(parsing) add criteria to excludedFields to keep expanded loot tables from breaking
  app/Http/Middleware/ParsePostRequestFields.php
Labels: bug, reviewed

#1111 feat(jquery-ui): allow jquery-ui mouse interactions to be used on touch screens
  public/css/lorekeeper.css
  public/js/jquery.ui.touch-punch.min.js
  resources/views/character/images.blade.php
  resources/views/home/characters.blade.php
  resources/views/layouts/app.blade.php
  resources/views/pages/credits.blade.php
Labels: enhancement, reviewed

#1116 fix(userprofile): Add check if previousUsername isnt identical to the current username
  resources/views/user/_profile_content.blade.php
Labels: bug, reviewed

#1114 Feat: allow items to use built-in rarities instead of individual system
  app/Console/Commands/ConvertItemRarities.php
  app/Http/Controllers/Admin/Data/ItemController.php
  app/Http/Controllers/Admin/Data/LootTableController.php
  app/Http/Middleware/ParsePostRequestFields.php
  app/Models/Item/Item.php
  app/Models/Loot/LootTable.php
  app/Services/ItemService.php
  app/Services/LootService.php
  config/lorekeeper/extensions.php
  resources/views/admin/items/create_edit_item.blade.php
  resources/views/admin/rarities/rarities.blade.php
  resources/views/world/_item_entry.blade.php
  resources/views/world/item_page.blade.php
Labels: enhancement, reviewed

#1112 feat(news/sales): Allow admin with manage rights to view news/sales that arent visible
  app/Http/Controllers/NewsController.php
  app/Http/Controllers/SalesController.php
  app/Models/News.php
  app/Models/Sales/Sales.php
  resources/views/admin/news/create_edit_news.blade.php
  resources/views/admin/sales/create_edit_sales.blade.php
  resources/views/news/_news.blade.php
  resources/views/sales/_sales.blade.php
Labels: enhancement, reviewed

#1079 fix(content warnings): included warnings not querying correctly
  app/Http/Controllers/BrowseController.php
Labels: bug, reviewed

#1125 item rarity searches
  app/Http/Controllers/Admin/Data/ItemController.php
  app/Http/Controllers/Characters/CharacterController.php
  app/Http/Controllers/Users/InventoryController.php
  app/Http/Controllers/Users/UserController.php
  app/Http/Controllers/WorldController.php
  resources/views/admin/items/items.blade.php
  resources/views/character/inventory.blade.php
  resources/views/home/inventory.blade.php
  resources/views/user/inventory.blade.php
  resources/views/world/items.blade.php
Labels: enhancement, reviewed

#1126 fix(file input): make file inputs visible on mobile devices
  public/js/bs-custom-file-input.min.js
  resources/views/account/settings.blade.php
  resources/views/admin/characters/create_edit_character_category.blade.php
  resources/views/admin/currencies/create_edit_currency.blade.php
  resources/views/admin/features/create_edit_feature.blade.php
  resources/views/admin/features/create_edit_feature_category.blade.php
  resources/views/admin/files/images.blade.php
  resources/views/admin/files/index.blade.php
  resources/views/admin/items/create_edit_item.blade.php
  resources/views/admin/items/create_edit_item_category.blade.php
  resources/views/admin/masterlist/create_character.blade.php
  resources/views/admin/prompts/create_edit_prompt.blade.php
  resources/views/admin/prompts/create_edit_prompt_category.blade.php
  resources/views/admin/rarities/create_edit_rarity.blade.php
  resources/views/admin/shops/create_edit_shop.blade.php
  resources/views/admin/specieses/create_edit_species.blade.php
  resources/views/admin/specieses/create_edit_subtype.blade.php
  resources/views/character/admin/_reupload_image_modal.blade.php
  resources/views/character/admin/upload_image.blade.php
  resources/views/character/design/image.blade.php
  resources/views/galleries/create_edit_submission.blade.php
  resources/views/layouts/app.blade.php
Labels: bug, dependencies, reviewed

#1133 Bug(Reports): Fix tabs not appropriately being set to active
  package-lock.json
  resources/views/home/reports.blade.php
Labels: bug

#1135 feat(pages): Allow admin with manage rights to view pages that arent visible
  app/Http/Controllers/PageController.php
  app/Models/SitePage.php
  resources/views/pages/page.blade.php
Labels: enhancement, reviewed

#1132 feat: avatar cropping
  app/Http/Controllers/Users/AccountController.php
  app/Services/UserService.php
  resources/views/account/settings.blade.php
Labels: enhancement, reviewed

#1136 fix(character): Nitpick- description says 'no additional notes given'
  resources/views/character/_tab_notes.blade.php
Labels: reviewed

#1142 feat: update robots.txt
  public/robots.txt
Labels: reviewed
