Repository lk-arpg/lorekeeper, pull requests merged in 2024-05, with the labels that each got.

#933 Adds minibadges to the user's characters page
  app/Models/Character/Character.php
  config/lorekeeper/extensions.php
  resources/views/pages/credits.blade.php
  resources/views/user/_characters.blade.php
Labels: enhancement, reviewed

#935 Credits page re-ordening
  resources/views/pages/credits.blade.php
Labels: reviewed

#936 Bug Fixes for Gallery Submissions on Prompts
  app/Http/Controllers/Users/SubmissionController.php
  app/Models/Submission/Submission.php
  resources/views/home/_submission_form.blade.php
Labels: bug, reviewed

#944 fix(reports): include parent scripts in scripts section
  resources/views/admin/reports/report.blade.php
Labels: bug, reviewed

#946 fixing gallery queue url in notif
  config/lorekeeper/notifications.php
Labels: bug, reviewed

#947 Bug(Character): Hidden characters not showing for admin
  app/Models/Character/Character.php
  package-lock.json
Labels: bug, reviewed

#948 Feat(items): Add option to block deletion
  app/Http/Controllers/Admin/Data/ItemController.php
  app/Models/Item/Item.php
  app/Services/ItemService.php
  database/migrations/2024_05_13_020617_add_deletable_to_items.php
  resources/views/admin/items/create_edit_item.blade.php
  resources/views/character/_inventory_stack.blade.php
  resources/views/home/_inventory_stack.blade.php
Labels: enhancement, reviewed

#949 Feat(items/currency): Block direct transfer by site settings
  app/Console/Commands/AddSiteSettings.php
  app/Http/Controllers/Users/BankController.php
  app/Http/Controllers/Users/InventoryController.php
  resources/views/home/_inventory_stack.blade.php
  resources/views/home/bank.blade.php
Labels: enhancement, reviewed

#954 fix liked comments
  resources/views/home/_sidebar.blade.php
Labels: bug, reviewed

#956 Increased database limits
  database/migrations/2024_05_16_220813_adjust_database_character_limits.php
Labels: bug, reviewed

#957 feat: Add ability for users to cancel their own design requests
  app/Http/Controllers/Characters/DesignController.php
  app/Services/DesignUpdateManager.php
  config/lorekeeper/extensions.php
  resources/views/character/design/_cancel_modal.blade.php
  resources/views/character/design/request.blade.php
  routes/lorekeeper/members.php
Labels: enhancement, reviewed

#958 Remove duplicate edit-credits in js
  resources/views/character/_image_js.blade.php
Labels: bug, reviewed
