Repository lk-arpg/lorekeeper, pull requests merged in 2025-01, with the labels that each got.

#1141 fix: stop loading all trade data into memory
  app/Http/Controllers/Admin/Characters/CharacterController.php
  app/Http/Controllers/Users/TradeController.php
  app/Models/Trade.php
  app/Services/TradeManager.php
  resources/views/home/trades/_trade.blade.php
Labels: reviewed

#1169 fix(characters): get format from file if storing design update fullsizes directly
  app/Services/DesignUpdateManager.php
Labels: bug, reviewed

#1166 Minor gallery fixes
  resources/views/comments/_form.blade.php
  resources/views/galleries/submission_log.blade.php
Labels: bug, reviewed

#1174 fix(users): eager load rank with users
  app/Models/User/User.php
Labels: reviewed

#1177 feat(design): Remove Manual Thumbnail Image Upload (+minor text alterations)
  config/lorekeeper/settings.php
  resources/views/character/design/image.blade.php
Labels: enhancement, reviewed

#1167 fix(models): Adding IdUrl to Prompts
  app/Models/Prompt/Prompt.php
  resources/views/prompts/_prompt_entry.blade.php
Labels: reviewed

#1180 fix(world): implement eager loading, refactor queries
  app/Http/Controllers/WorldController.php
  app/Models/Item/Item.php
  app/Models/Species/Subtype.php
  config/lorekeeper/extensions.php
  resources/views/world/_item_entry.blade.php
  resources/views/world/_species_entry.blade.php
  resources/views/world/item_page.blade.php
  resources/views/world/items.blade.php
Labels: reviewed

#1171 feat(users): add "is admin" flag to ranks
  app/Console/Commands/SetIsAdmin.php
  app/Console/Commands/SetupAdminUser.php
  app/Models/Rank/Rank.php
  app/Services/RankService.php
  database/migrations/2025_01_02_210931_add_is_admin_to_ranks.php
Labels: enhancement, reviewed

#1173 fix(galleries): ignore protocol when finding prompt submissions using a gallery submission
  app/Models/Gallery/GallerySubmission.php
Labels: bug, reviewed

#1176 fix(galleries): prevent editing rejected submissions
  app/Http/Controllers/GalleryController.php
  app/Services/GalleryManager.php
  resources/views/galleries/submission.blade.php
Labels: bug, reviewed

#1181 fix(characters): improve design update thumb filename masterlist image format check
  app/Models/Character/CharacterDesignUpdate.php
Labels: bug, reviewed

#1182 fix(characters): correct use of masterlist image dimension target setting
  app/Services/CharacterManager.php
Labels: bug, reviewed

#1183 fix(browse): add additional eager loading
  app/Http/Controllers/BrowseController.php
Labels: reviewed

#1185 fix(prompts): remove extraneous $ before idUrl property
  resources/views/prompts/_prompt_entry.blade.php
Labels: bug, reviewed

#1168 feat(Pages/News): Regenerate Function
  app/Http/Controllers/Admin/NewsController.php
  app/Http/Controllers/Admin/PageController.php
  app/Services/NewsService.php
  app/Services/PageService.php
  resources/views/admin/news/_regen_news.blade.php
  resources/views/admin/news/create_edit_news.blade.php
  resources/views/admin/pages/_regen_page.blade.php
  resources/views/admin/pages/create_edit_page.blade.php
  routes/lorekeeper/admin.php
Labels: enhancement, reviewed

#1186 feat(currencies): add currency categories
  app/Http/Controllers/Admin/Data/CurrencyController.php
  app/Http/Controllers/WorldController.php
  app/Models/Currency/Currency.php
  app/Models/Currency/CurrencyCategory.php
  app/Models/User/User.php
  app/Services/CurrencyService.php
  database/migrations/2025_01_10_121504_create_currency_categories_table.php
  resources/views/admin/currencies/_delete_currency_category.blade.php
  resources/views/admin/currencies/create_edit_currency.blade.php
  resources/views/admin/currencies/create_edit_currency_category.blade.php
  resources/views/admin/currencies/currencies.blade.php
  resources/views/admin/currencies/currency_categories.blade.php
  resources/views/home/bank.blade.php
  resources/views/user/bank.blade.php
  resources/views/world/_currency_entry.blade.php
  resources/views/world/_sidebar.blade.php
  resources/views/world/currencies.blade.php
  resources/views/world/currency_categories.blade.php
  routes/lorekeeper/admin.php
  routes/lorekeeper/browse.php
  routes/lorekeeper/members.php
Labels: enhancement, reviewed

#1188 feat(currency): Allow 'edit_data' staff to view user banks
  app/Http/Controllers/Users/UserController.php
  app/Http/Controllers/WorldController.php
  app/Models/User/User.php
  resources/views/user/_profile_content.blade.php
  resources/views/user/bank.blade.php
Labels: enhancement, reviewed

#1190 fix: flat array by default & extension compatibility
  app/Models/User/User.php
  resources/views/home/bank.blade.php
  resources/views/user/_profile_content.blade.php
  resources/views/user/bank.blade.php
Labels: bug, reviewed

#1175 fix(galleries): implement eager loading, refactor queries
  app/Http/Controllers/GalleryController.php
  app/Models/Gallery/Gallery.php
  app/Models/Gallery/GalleryCollaborator.php
  app/Models/Gallery/GallerySubmission.php
  app/Services/GalleryManager.php
  resources/views/galleries/_queue_submission.blade.php
  resources/views/galleries/_submission_favorites.blade.php
  resources/views/galleries/_thumb.blade.php
  resources/views/galleries/gallery.blade.php
  resources/views/galleries/index.blade.php
  resources/views/galleries/submission.blade.php
  resources/views/galleries/submission_log.blade.php
  resources/views/galleries/submissions.blade.php
Labels: reviewed

#1191 fix: criteria loot
  app/Console/Commands/FixEqualsCriteriaLoots.php
  app/Models/Invitation.php
  app/Models/Loot/Loot.php
  resources/views/admin/loot_tables/create_edit_loot_table.blade.php
Labels: bug, reviewed

#1192 feat: convert decodes / encodes to casts
  app/Helpers/AssetHelpers.php
  app/Helpers/Notifications.php
  app/Http/Controllers/Admin/Users/UserController.php
  app/Http/Controllers/Comments/CommentController.php
  app/Models/Character/CharacterDesignUpdate.php
  app/Models/Character/CharacterItem.php
  app/Models/Character/CharacterLog.php
  app/Models/Character/CharacterTransfer.php
  app/Models/Comment/CommentEdit.php
  app/Models/Gallery/GallerySubmission.php
  app/Models/Item/Item.php
  app/Models/Item/ItemTag.php
  app/Models/Notification.php
  app/Models/Report/Report.php
  app/Models/Sales/SalesCharacter.php
  app/Models/Submission/Submission.php
  app/Models/Submission/SubmissionCharacter.php
  app/Models/User/UserItem.php
  app/Models/User/UserUpdateLog.php
  app/Services/CharacterManager.php
  app/Services/DesignUpdateManager.php
  app/Services/GalleryManager.php
  app/Services/InventoryManager.php
  app/Services/Item/BoxService.php
  app/Services/Item/SlotService.php
  app/Services/ItemService.php
  app/Services/LinkService.php
  app/Services/LootService.php
  app/Services/SalesService.php
  app/Services/SubmissionManager.php
  app/Services/UserService.php
Labels: reviewed

#1206 chore(deps): update laravel/fortify
  composer.json
  composer.lock
Labels: dependencies, reviewed

#1208 fix(characters): do JSON encode during character log creation
  app/Services/CharacterManager.php
Labels: bug, reviewed

#1209 feat: allow head section
  resources/views/layouts/app.blade.php
Labels: enhancement, reviewed

#1198 Add Tinymce code editor ext
  public/css/lorekeeper.css
  public/js/plugins/codeeditor/plugin.min.js
  resources/views/character/_image_js.blade.php
  resources/views/js/_modal_wysiwyg.blade.php
  resources/views/layouts/app.blade.php
  resources/views/pages/credits.blade.php
Labels: enhancement, reviewed

#1202 feat: display icons for currency stock costs
  app/Helpers/AssetHelpers.php
Labels: enhancement, reviewed

#1203 feat: misc QoL
  app/Console/Commands/AddSiteSettings.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/Users/AccountController.php
  app/Http/Middleware/CheckAlias.php
  app/Models/Rarity.php
  app/Models/User/User.php
  app/Models/User/UserSettings.php
  app/Policies/CommentPolicy.php
  app/Services/UserService.php
  config/lorekeeper/settings.php
  database/migrations/2025_01_21_005343_add_allow_profile_comments_option_to_user_settings.php
  resources/views/account/settings.blade.php
  resources/views/admin/rarities/create_edit_rarity.blade.php
  resources/views/auth/email.blade.php
  resources/views/user/_profile_content.blade.php
  resources/views/world/_rarity_entry.blade.php
  resources/views/world/rarities.blade.php
  routes/lorekeeper/members.php
  routes/web.php
Labels: enhancement, reviewed

#1207 feat(dynamic limits): update to latest
  app/Http/Controllers/Admin/LimitController.php
  app/Models/Limit/Limit.php
  app/Services/LimitManager.php
  app/Services/LimitService.php
  database/migrations/2024_10_06_150833_add_auto_unlock_option_to_limits.php
  resources/views/widgets/_add_limits.blade.php
  resources/views/widgets/_limits.blade.php
  routes/lorekeeper/members.php
Labels: enhancement, reviewed

#1218 fix(galleries): remove vote data JSON encode
  app/Services/GalleryManager.php
Labels: bug, reviewed

#1219 feat: item purchasing
  app/Helpers/AssetHelpers.php
  app/Http/Controllers/ShopController.php
  app/Services/ShopManager.php
  config/lorekeeper/ext-tracker/shop_features.php
  resources/views/admin/shops/_stock_modal.blade.php
  resources/views/character/design/addons.blade.php
  resources/views/character/inventory.blade.php
  resources/views/home/create_submission.blade.php
  resources/views/home/edit_submission.blade.php
  resources/views/home/trades/create_trade.blade.php
  resources/views/home/trades/edit_trade.blade.php
  resources/views/home/trades/trade.blade.php
  resources/views/shops/_stock_modal.blade.php
  resources/views/widgets/_inventory_select.blade.php
Labels: enhancement, reviewed

#1217 fix(characters): add vote data to design update casts, refactor handling
  app/Models/Character/CharacterDesignUpdate.php
  app/Services/DesignUpdateManager.php
  resources/views/admin/designs/index.blade.php
  resources/views/character/design/_header.blade.php
Labels: bug, reviewed

#1221 Update create_edit_shop.blade.php
  resources/views/admin/shops/create_edit_shop.blade.php
Labels: bug, reviewed
