Repository lk-arpg/lorekeeper, pull requests merged in 2025-02, with the labels that each got.

#1224 General feature/feeds page
  app/Http/Controllers/PageController.php
  resources/views/layouts/_footer.blade.php
  resources/views/pages/feeds.blade.php
  routes/lorekeeper/browse.php
Labels: enhancement, reviewed

#1216 fix: tinymce sub modals
  resources/views/layouts/app.blade.php
Labels: bug, reviewed

#1210 TinyMCE consolidation
  .bladeignore
  app/Http/Controllers/Admin/Characters/CharacterController.php
  app/Http/Controllers/Admin/Characters/CharacterImageController.php
  config/lorekeeper/extensions.php
  resources/views/account/settings.blade.php
  resources/views/admin/characters/create_edit_character_category.blade.php
  resources/views/admin/currencies/create_edit_currency.blade.php
  resources/views/admin/currencies/create_edit_currency_category.blade.php
  resources/views/admin/designs/_approve_request_modal.blade.php
  resources/views/admin/features/create_edit_feature.blade.php
  resources/views/admin/features/create_edit_feature_category.blade.php
  resources/views/admin/items/create_edit_item.blade.php
  resources/views/admin/items/create_edit_item_category.blade.php
  resources/views/admin/items/tags/slot.blade.php
  resources/views/admin/limits/create_edit_limit.blade.php
  resources/views/admin/masterlist/create_character.blade.php
  resources/views/admin/news/create_edit_news.blade.php
  resources/views/admin/pages/create_edit_page.blade.php
  resources/views/admin/prompts/create_edit_prompt.blade.php
  resources/views/admin/prompts/create_edit_prompt_category.blade.php
  resources/views/admin/rarities/create_edit_rarity.blade.php
  resources/views/admin/reports/report.blade.php
  resources/views/admin/sales/create_edit_sales.blade.php
  resources/views/admin/shops/create_edit_shop.blade.php
  resources/views/admin/specieses/create_edit_species.blade.php
  resources/views/admin/specieses/create_edit_subtype.blade.php
  resources/views/admin/submissions/submission.blade.php
  resources/views/character/_image_js.blade.php
  resources/views/character/admin/_edit_description.blade.php
  resources/views/character/admin/_edit_notes.blade.php
  resources/views/character/admin/upload_image.blade.php
  resources/views/character/edit_profile.blade.php
  resources/views/comments/comments.blade.php
  resources/views/comments/permalink_comment.blade.php
  resources/views/galleries/create_edit_submission.blade.php
  resources/views/js/_modal_wysiwyg.blade.php
  resources/views/js/_tinymce_wysiwyg.blade.php
  resources/views/layouts/app.blade.php
  resources/views/pages/credits.blade.php
Labels: reviewed

#1233 Fix incorrect breadcrumbs on Admin pages
  resources/views/admin/users/user_ban.blade.php
  resources/views/admin/users/user_deactivate.blade.php
  resources/views/admin/users/user_update_log.blade.php
Labels: reviewed
