Repository lk-arpg/lorekeeper, pull requests merged in 2025-05, with the labels that each got.

#1252 fixes
  app/Http/Controllers/Auth/LoginController.php
  app/Models/Shop/ShopLog.php
  app/Services/InventoryManager.php
Labels: bug, needs review

#1269 fix(admin): Rarity edit object not filled in admin section
  resources/views/admin/rarities/create_edit_rarity.blade.php
Labels: bug, reviewed

#1265 optimization(all): Replaced OldestFirst with NewestFirst reversed
  app/Http/Controllers/Admin/Characters/CharacterController.php
  app/Http/Controllers/Admin/Data/FeatureController.php
  app/Http/Controllers/Admin/Data/ItemController.php
  app/Http/Controllers/Admin/DesignController.php
  app/Http/Controllers/Admin/GalleryController.php
  app/Http/Controllers/Admin/ReportController.php
  app/Http/Controllers/Admin/SubmissionController.php
  app/Http/Controllers/PromptsController.php
  app/Http/Controllers/SalesController.php
  app/Http/Controllers/WorldController.php
  app/Models/Character/CharacterDesignUpdate.php
  app/Models/Character/CharacterTransfer.php
  app/Models/Currency/Currency.php
  app/Models/Feature/Feature.php
  app/Models/Gallery/GallerySubmission.php
  app/Models/Item/Item.php
  app/Models/Prompt/Prompt.php
  app/Models/Report/Report.php
  app/Models/Sales/Sales.php
  app/Models/Submission/Submission.php
Labels: enhancement, reviewed

#1235 fix: make the trait info full length
  resources/views/character/_image_info.blade.php
Labels: reviewed

#1280 fix(ranks): parsed rank description upon initial setup
  app/Console/Commands/SetupAdminUser.php
Labels: bug, reviewed

#1285 fix(prompts): add prompt meta image to individual prompt pages
  package-lock.json
  resources/views/prompts/prompt.blade.php
Labels: enhancement, reviewed
